heat_template_version: 2016-04-08

description: >
  OpenStack Neutron Compute Cisco ACI plugin

parameters:
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  ACIApicSystemId:
    type: string
    default: 'aci_openstack'
  ACIApicInfraVlan:
    type: number
    default: 4093
  ACIApicInfraSubnetGateway:
    type: string
    default: '10.0.0.30'
  ACIApicInfraAnycastAddr:
    type: string
    default: '10.0.0.32'
  ACIOpflexUplinkInterface:
    type: string
    default: 'nic1'
  ACIOpflexBridgeToPatch:
    type: string
    default: 'br-ex'
    description: >
     When opflex is used in VLAN encap mode, the interface connected to ACI fabric should
     be part of integration bridge br-int. In some network configuration, the interface could
     already be part of other bridge for example br-ex. Setting this value to br-ex will create
     a patch interface between br-int and br-ex. If set to empty string, no patch will be created
  ACIOpflexEncapMode:
    type: string
    default: 'vxlan'  
    constraints:
      - allowed_values: ['vlan', 'vxlan']
  ACIUseLldp:
    type: boolean
    default: true
    description: >
      When true, use lldp to discover host links that are connected to aci fabric.
      if set to false, ACIHostLinks needs to be set to describe the host connectivity to fabric
  AciOpenvswitch:
    type: boolean
    default: false
  ACIEnableBondWatchService:
    type: boolean
    default: false
    description: Enable and start apic-bond-watch service
  IntelCnaNicDisableLLDP:
    type: boolean
    default: true
resources:
  NeutronBase:
    type: /usr/share/openstack-tripleo-heat-templates/puppet/services/neutron-base.yaml
    properties:
      ServiceNetMap: {get_param: ServiceNetMap}
      DefaultPasswords: {get_param: DefaultPasswords}
      EndpointMap: {get_param: EndpointMap}

outputs:
  role_data:
    description: Role data for the Neutron compute Cisco ACI plugin
    value:
      service_name: neutron_plugin_compute_ciscoaci
      config_settings:
        map_merge:
          - get_attr: [NeutronBase, role_data, config_settings]
            ciscoaci::opflex::aci_apic_systemid: {get_param: ACIApicSystemId}
            ciscoaci::opflex::aci_apic_infravlan: {get_param: ACIApicInfraVlan}
            ciscoaci::opflex::aci_apic_infra_subnet_gateway: {get_param: ACIApicInfraSubnetGateway}
            ciscoaci::opflex::aci_apic_infra_anycast_address: {get_param: ACIApicInfraAnycastAddr}    
            ciscoaci::opflex::aci_opflex_uplink_interface: {get_param: ACIOpflexUplinkInterface}
            ciscoaci::opflex::aci_opflex_encap_mode: {get_param: ACIOpflexEncapMode}
            ciscoaci::opflex::opflex_target_bridge_to_patch: {get_param: ACIOpflexBridgeToPatch}
            ciscoaci::opflex::opflex_enable_bond_watch: {get_param: ACIEnableBondWatchService}
            ciscoaci::compute::use_lldp_discovery: {get_param: ACIUseLldp}
            ciscoaci::compute::use_openvswitch: {get_param: AciOpenvswitch}
            ciscoaci::compute::intel_cna_nic_disable_lldp: {get_param: IntelCnaNicDisableLLDP}
      step_config: |
        include tripleo::profile::base::ciscoaci_compute
